name: Deploy demo

on:
  push:
    branches:
    - test
  workflow_dispatch:
  schedule:
    - cron:  '15 0 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |-
        npm install -g heroku
        heroku plugins:install heroku-builds
        datasette publish heroku district_sample_csv.db \
          -n high-school-datasette \
          --install=datasette-vega \
          --install=datasette-jellyfish \
          --install=datasette-graphql \
          --install='datasette-copyable>=0.2' \
          --version-note=nonotes \
          --branch=test